version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    depends_on:
      - postgres
    environment:
      KEY: supersecretkey
      ADMIN_EMAIL: svbjp@yandex.ru
      ADMIN_PASSWORD: forthepassword
      DB_CLIENT: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus
    volumes:
      - ./directus/uploads:/directus/uploads

volumes:
  pgdata: