jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install depends
        run: npm install --legacy-peer-deps

      - name: check TS types
        run: npm run typecheck

      - name: build a project
        run: npm run build